from pathlib import Path
p=Path('outputs/보나센_원가계산기.html');s=p.read_text(encoding='utf-8')
def change(old,new):
 global s
 if old not in s: raise RuntimeError('Missing '+old[:90])
 s=s.replace(old,new)
change('<section><details>', '''<section aria-labelledby="chartTitle"><h2 id="chartTitle">7. 매출·비용·이익 한눈에 보기</h2><p class="note" id="chartPeriod"></p><div class="notice" id="chartResult" aria-live="polite"></div><div id="overviewChart" role="figure" aria-label="기간 매출, 비용 항목, 고정비 차감 후 이익 비교 그래프"></div><p class="note">모든 막대는 같은 금액 기준입니다. 중앙선 오른쪽은 양수, 왼쪽 빨간 막대는 손실입니다. 생산비 전체 대신 판매된 제품의 제조원가를 반영하며, 추가 튜브 생산비는 별도 표를 확인하세요.</p></section><section><details>''')
change('tfoot{font-weight:700}', '''.chart-row{padding:12px 0;border-bottom:1px solid #e0e8ef}.chart-row.chart-final{margin-top:10px;padding:16px 12px;background:#e7f4f7;border-radius:8px;border-bottom:0}.chart-heading{display:flex;justify-content:space-between;gap:12px;align-items:baseline;margin-bottom:8px;font-size:15px}.chart-heading strong{white-space:nowrap}.chart-track{height:24px;position:relative;background:linear-gradient(to right,#f8edf0 50%,#edf2f7 50%);border-radius:4px;overflow:hidden}.chart-track:after{content:'';position:absolute;left:50%;top:0;bottom:0;border-left:2px solid #9badbd}.chart-fill{position:absolute;height:100%;border-radius:3px}.chart-scale{display:flex;justify-content:space-between;color:#5a7083;font-size:13px;margin:8px 0}.chart-final .chart-heading{font-weight:700}tfoot{font-weight:700}''')
change("function input(value,k,group,i,extra='')", '''function chartModel(s){const c=calculate(s),f=fixedTotals(s);return [{label:'매출 총계',value:c.income,color:'#163f62'},{label:'판매 제품 제조원가',value:c.cogs,color:'#496c92'},{label:'판매수수료·배송·포장비',value:c.fee+c.ship+c.pack,color:'#168e9c'},{label:'광고·마케팅비 (리뷰 포함)',value:c.ad,color:'#d09620'},{label:'제품 관리비',value:c.admin,color:'#8593b3'},{label:'월 고정비 (기간 합계)',value:f.period,color:'#8069a6'},{label:'고정비 차감 후 이익',value:c.profit-f.period,color:'#08747a'}];}
function renderChart(s){const rows=chartModel(s),c=calculate(s),f=fixedTotals(s),net=rows[6].value,maximum=Math.max(1,...rows.map(r=>Math.abs(r.value)));$('chartPeriod').textContent=(s.period?s.period+' · ':'')+s.months+'개월 합계 · 부가세 포함 금액 · 세금 정산 전';$('chartResult').textContent='매출 '+money(c.income)+'원 − 전체 비용 '+money(c.total+f.period)+'원 = '+(net<0?'손실 ':'이익 ')+money(Math.abs(net))+'원';$('chartResult').className=net<0?'warn':'notice';$('overviewChart').innerHTML=rows.map((r,i)=>{const width=Math.abs(r.value)/maximum*50,left=r.value<0?50-width:50;return `<div class="chart-row ${i===6?'chart-final':''}"><div class="chart-heading"><span>${r.label}</span><strong class="${r.value<0?'negative':i===6?'positive':''}">${money(r.value)} 원</strong></div><div class="chart-track" role="img" aria-label="${r.label}: ${money(r.value)}원"><div class="chart-fill" style="left:${left}%;width:${width}%;background:${r.value<0?'#bd4934':r.color}" title="${r.label}: ${money(r.value)}원"></div></div></div>`;}).join('')+`<div class="chart-scale"><span>−${money(maximum)}원</span><span>0</span><span>${money(maximum)}원</span></div>`;}
function input(value,k,group,i,extra='')''')
change('renderTotals(c);const segments=', 'renderTotals(c);renderChart(state);const segments=')
change("$('costs').innerHTML='';$('bundles').innerHTML='';", "$('overviewChart').innerHTML='';$('chartResult').textContent='입력값을 확인하면 그래프가 표시됩니다.';$('chartPeriod').textContent='';$('costs').innerHTML='';$('bundles').innerHTML='';")
p.write_text(s,encoding='utf-8');print('Added live overview graph: revenues, costs and signed profit; invalid inputs clear graph')
