from pathlib import Path
p=Path('outputs/보나센_원가계산기.html');s=p.read_text(encoding='utf-8')
def change(a,b):
 global s
 if a not in s: raise RuntimeError('Missing '+a[:90])
 s=s.replace(a,b)
change('<p class="note" id="chartPeriod"></p>', '''<div class="grid"><label>월 판매수량 (제품 개수)<input id="forecastMonthlyUnits" type="number" min="0" step="1"></label><label>개당 제조원가 (VAT 포함, 원)<input id="forecastUnitCost" type="number" min="0" step="any"></label><label>적용 개월수<input id="forecastMonths" type="number" min="1" step="1"></label><label>광고·배송·관리비 포함 개당 총원가<input id="forecastFullCost" readonly aria-readonly="true"></label></div><p class="note">위쪽 입력값과 함께 연동됩니다. 개당 제조원가는 완제품 단가와 제조·검사 추가비를 포함합니다. 월 판매수량을 변경하면 기존 묶음 판매비율을 최대한 유지하며, 남는 수량은 1개 구성에 반영합니다. 기존 판매계획이 없으면 1개 구성으로 계산합니다. 여러 달은 같은 월 판매수량을 가정합니다.</p><p id="forecastStatus" role="status" class="note"></p><p class="note" id="chartPeriod"></p>''')
change('function chartModel(s)', '''function setMonthlyUnits(s,monthly){if(!Number.isFinite(monthly)||monthly<0||!Number.isInteger(monthly))throw Error('월 판매수량은 0 이상의 정수로 입력하세요.');const target=monthly*s.months,current=calculate(s).sold,single=s.sales.findIndex(r=>r.units===1);if(single<0)throw Error('판매수량을 정확히 맞추려면 위 판매계획에 1개 구성을 추가하세요.');const orders=s.sales.map(r=>current?Math.floor(r.orders*target/current):0);const assigned=s.sales.reduce((sum,r,i)=>sum+r.units*orders[i],0);orders[single]+=target-assigned;s.sales.forEach((r,i)=>r.orders=orders[i]);}
function setUnitCost(s,value){if(!Number.isFinite(value)||value<0)throw Error('개당 제조원가는 0 이상의 숫자로 입력하세요.');const extra=s.manufactureExtra/s.production;if(value<extra)throw Error('개당 제조원가는 제조·검사 추가비의 개당 부담액 '+money(extra)+'원 이상이어야 합니다.');s.manufacture=(value-extra)/(1+s.vat/100);s.vendor='custom';}
function chartModel(s)''')
change("function renderChart(s){const rows=", "function renderChart(s){const totals=calculate(s);if(document.activeElement!==$('forecastMonthlyUnits'))$('forecastMonthlyUnits').value=Number((totals.sold/s.months).toFixed(4));if(document.activeElement!==$('forecastUnitCost'))$('forecastUnitCost').value=Number(totals.unit.toFixed(4));$('forecastMonths').value=s.months;$('forecastFullCost').value=totals.per===null?'판매수량을 입력하세요':money(totals.per)+' 원';const rows=")
change("$('overviewChart').innerHTML='';", "$('forecastFullCost').value='입력값을 확인하세요';$('overviewChart').innerHTML='';")
change("document.addEventListener('input',e=>{const el=e.target;", """document.addEventListener('input',e=>{const el=e.target;if(['forecastMonthlyUnits','forecastUnitCost','forecastMonths'].includes(el.id)){try{if(el.value==='')throw Error('값을 입력하세요.');const value=Number(el.value);validate(state);if(el.id==='forecastMonthlyUnits')setMonthlyUnits(state,value);if(el.id==='forecastUnitCost')setUnitCost(state,value);if(el.id==='forecastMonths'){if(!Number.isInteger(value)||value<1)throw Error('적용 개월수는 1 이상의 정수로 입력하세요.');const monthly=calculate(state).sold/state.months;state.months=value;if(Number.isInteger(monthly)&&state.sales.some(r=>r.units===1))setMonthlyUnits(state,monthly);}render();$('forecastStatus').textContent='위 판매계획과 제조단가에 반영했습니다. 그래프와 이익이 갱신되었습니다.';$('forecastStatus').className='note';}catch(err){$('forecastStatus').textContent=err.message+' 기존 계산값은 유지됩니다.';$('forecastStatus').className='warn';}return;}""")
p.write_text(s,encoding='utf-8');print('Added linked monthly sales, manufacturing unit cost, months and calculated full unit cost above graph')
