const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('outputs/보나센_원가계산기.html','utf8');
const js=html.match(/<script>([\s\S]*?)<\/script>/)[1],els=new Map(),handlers={};
function register(markup){for(const m of markup.matchAll(/\bid=["']([^"']+)["']/g)){if(els.has(m[1]))continue;let inner='';const el={id:m[1],value:'',dataset:{},checked:false,textContent:'',addEventListener(){},setAttribute(){},click(){},selectedOptions:[{text:'네오메디칼제약'}]};Object.defineProperty(el,'innerHTML',{get:()=>inner,set:v=>{inner=String(v);register(inner);}});els.set(m[1],el);}}
register(html.split('<script>')[0]);
const get=id=>els.get(id)||null;
const ctx={document:{getElementById:get,addEventListener:(n,f)=>handlers[n]=f,createElement:()=>({click(){}})},localStorage:{getItem:()=>null,setItem(){}},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},setTimeout(){},alert:m=>{throw Error(m)},confirm:()=>true,window:{print(){}}};
vm.createContext(ctx);vm.runInContext(js,ctx);
assert.ok(get('forecastSales').innerHTML.includes('data-forecast-index'));
assert.ok(get('dailyBody').innerHTML.includes('2026-10-31'));
assert.ok(get('overviewChart').innerHTML.includes('chart-row'));
handlers.input({target:{id:'dashboardTarget',dataset:{},value:'200000'}});
handlers.input({target:{id:'',dataset:{dailyDate:'2026-10-01',dailyBundle:'bundle-1'},value:'10'}});
assert.equal(get('dashRevenue').textContent,'198,000 원');
assert.equal(get('dashRate').textContent,'99.0%');
assert.ok(get('overviewChart').innerHTML.includes('198,000'));
handlers.input({target:{id:'monthlyRevenueGoal',dataset:{},value:'400000'}});
assert.equal(get('dashboardTarget').value,400000);
assert.equal(get('dashRate').textContent,'49.5%');
assert.equal(get('actualVariable-fee').textContent,'23,760');
handlers.input({target:{id:'',dataset:{dailyDate:'2026-10-02',dailyBundle:'bundle-1'},value:'5'}});
assert.equal(get('actualVariable-fee').textContent,'35,640');
assert.equal(get('actualVariable-ship').textContent,'45,000');
assert.equal(get('actualVariable-pack').textContent,'8,250');
const chart=get('overviewChart').innerHTML;
for(const label of ['매출목표','누적 매출','지출비용','이익 계산 결과','월 고정비 차감 후 이익'])assert.ok(chart.includes(label));
assert.equal((chart.match(/class="chart-group"/g)||[]).length,4);
assert.ok(chart.includes('기준일까지 월 누적 매출 − 총 지출비용 = 월 고정비 차감 후 이익'));
assert.ok(!chart.includes('지출비용 합계:'));
get('salesChannel').value='naver';get('salesChannel').onchange();
assert.ok(get('dailyBody').innerHTML.includes('bundle-1-naver'));
assert.ok(get('dailyBody').innerHTML.includes('data-daily-bundle="bundle-1"'));
assert.ok(get('dailyBody').innerHTML.includes('data-daily-bundle="bundle-1-other"'));
assert.ok(get('dailyHead').innerHTML.includes('<th>판매처</th>'));
assert.equal((get('dailyBody').innerHTML.match(/class="daily-channel /g)||[]).length,93);
assert.equal((get('dailyBody').innerHTML.match(/class="daily-subtotal"/g)||[]).length,31);
handlers.input({target:{id:'',dataset:{dailyDate:'2026-10-02',dailyBundle:'bundle-1-naver'},value:'10'}});
assert.equal(get('actualVariable-fee').textContent,'45,540');
assert.equal(get('dashRevenue').textContent,'495,000 원');
assert.equal(get('channelIncome-2026-10-02-naver').textContent,'198,000');
assert.equal(get('channelIncome-2026-10-02-coupang').textContent,'99,000');
assert.equal(get('dailyIncome-2026-10-02').textContent,'297,000');
assert.ok(get('channelSummary').innerHTML.includes('9,900'));
assert.ok(get('channelSummaryFoot').innerHTML.includes('495,000'));
get('salesChannel').value='other';get('salesChannel').onchange();
handlers.input({target:{id:'',dataset:{dailyDate:'2026-10-02',dailyBundle:'bundle-1-other'},value:'1'}});
assert.equal(get('actualVariable-fee').textContent,'45,540');
assert.equal(get('dashRevenue').textContent,'514,800 원');
get('salesChannel').value='coupang';get('salesChannel').onchange();
assert.ok(get('dailyBody').innerHTML.includes('data-daily-bundle="bundle-1"'));
assert.ok(!html.includes('4. 월 예상매출과 일일 누계 달성현황'));
console.log('PASS: startup with only existing HTML IDs, dynamically created table IDs, forecast table, 31 daily rows, graph and cumulative input updates');
