const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('outputs/보나센_원가계산기.html','utf8');
const js=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(js);
const sandbox={localStorage:{getItem:()=>null},document:{},console};vm.createContext(sandbox);
vm.runInContext(js.slice(0,js.indexOf('function input('))+';globalThis.api={defaults,calculate,validate,fixedTotals,operatingTotals,moveRow,chartModel,setMonthlyOrders,setForecastMonths,setUnitCost,revenueTarget,daysInMonth,setDailySale,dailyTotals,ledgerItems,ensureLedgerYear,ledgerGraphState,ledgerColumns,dailyRevenueTarget,dailyGoal,selectedLedgerDate,cumulativeRevenueTarget,cumulativeLedgerItems,monthlyBudget,costBasis,reportingSales};',sandbox);
const {defaults,calculate,validate}=sandbox.api;const s=defaults();
const cumulative=defaults();validate(cumulative);cumulative.ledger.day=1;const cb=sandbox.api.monthlyBudget(cumulative,10);Object.assign(cb,{cogs:500000,fee:50000,ship:60000,pack:10000,ad:100000,admin:20000,fixed:200000});sandbox.api.ensureLedgerYear(cumulative).targets[9]=1000000;sandbox.api.setDailySale(cumulative,'2026-10-01','bundle-1',10);sandbox.api.setDailySale(cumulative,'2026-10-02','bundle-1',20);sandbox.api.setDailySale(cumulative,'2026-10-10','bundle-0',50);let cc=calculate(sandbox.api.costBasis(cumulative));assert.equal(cc.revenue,198000);assert.equal(cc.sold,30);assert.equal(Math.round(cc.total),Math.round(cc.sold*cc.unit+240000));assert.equal(Math.round(cc.cogs/cc.sold),1716);assert.equal(sandbox.api.fixedTotals(sandbox.api.costBasis(cumulative)).period,200000);assert.equal(sandbox.api.cumulativeRevenueTarget(cumulative).ratio,0.198);cumulative.ledger.day=2;cc=calculate(sandbox.api.costBasis(cumulative));assert.equal(cc.revenue,594000);assert.equal(cc.sold,90);assert.equal(Math.round(cc.total),Math.round(cc.sold*cc.unit+240000));assert.equal(Math.round(cc.cogs/cc.sold),1716);assert.equal(Math.round(sandbox.api.operatingTotals(sandbox.api.costBasis(cumulative)).period),-440);assert.equal(sandbox.api.reportingSales(cumulative).find(r=>r.id==='bundle-1').orders,30);assert.equal(sandbox.api.reportingSales(cumulative).find(r=>r.id==='bundle-0').orders,0);cumulative.sales[1].price=25000;sandbox.api.setDailySale(cumulative,'2026-10-03','bundle-1',1);cumulative.ledger.day=3;assert.equal(calculate(sandbox.api.costBasis(cumulative)).revenue,619000);assert.equal(sandbox.api.reportingSales(cumulative).filter(r=>r.id==='bundle-1').length,2);assert.equal(Math.round(calculate(sandbox.api.costBasis(cumulative)).total),399588);cumulative.ledger.day=10;assert.equal(calculate(sandbox.api.costBasis(cumulative)).revenue,1009000);assert.equal(sandbox.api.cumulativeRevenueTarget(cumulative).ratio,1.009);assert.equal(sandbox.api.reportingSales(cumulative).reduce((a,r)=>a+r.orders*r.units,0),143);cumulative.ledger.month=0;assert.equal(calculate(sandbox.api.costBasis(cumulative)).revenue,1009000);validate(JSON.parse(JSON.stringify(cumulative)));console.log('PASS: month-to-date sales versus full monthly goal, future dates excluded, quantities and historical prices match reporting, manufacturing always 1716 per cumulative product, other monthly costs fixed, cumulative profit, annual scope and budget backup');
const daily=defaults();validate(daily);const dy=sandbox.api.ensureLedgerYear(daily);dy.targets[9]=3100000;daily.ledger.day=1;sandbox.api.setDailySale(daily,'2026-10-01','bundle-1',5);let dg=sandbox.api.dailyRevenueTarget(daily);assert.equal(dg.target,100000);assert.equal(dg.actual,99000);assert.equal(dg.ratio,0.99);dy.dailyTargets['2026-10-01']=50000;assert.equal(sandbox.api.dailyRevenueTarget(daily).ratio,1.98);dy.dailyTargets['2026-10-01']=0;assert.equal(sandbox.api.dailyRevenueTarget(daily).ratio,null);assert.equal(dy.targets[9],3100000);daily.ledger.day=2;dg=sandbox.api.dailyRevenueTarget(daily);assert.equal(dg.recorded,false);const monthlyBefore=calculate(sandbox.api.ledgerGraphState(daily)).profit;daily.ledger.day=1;assert.equal(calculate(sandbox.api.ledgerGraphState(daily)).profit,monthlyBefore);const backupDay=validate(JSON.parse(JSON.stringify(daily)));assert.equal(sandbox.api.ensureLedgerYear(backupDay).dailyTargets['2026-10-01'],0);console.log('PASS: day-specific targets and attainment, automatic monthly/31 allocation, overrides including zero, missing daily sales, unchanged monthly cost/profit and saved daily targets');
const ledger=defaults();validate(ledger);assert.equal(sandbox.api.daysInMonth(2028,2),29);assert.equal(sandbox.api.daysInMonth(2026,2),28);sandbox.api.setDailySale(ledger,'2026-10-01','bundle-1',10);sandbox.api.setDailySale(ledger,'2026-10-02','bundle-0',2);sandbox.api.setDailySale(ledger,'2026-11-01','bundle-1',5);let monthSales=sandbox.api.dailyTotals(sandbox.api.ledgerItems(ledger,10));assert.equal(monthSales.sets,12);assert.equal(monthSales.units,32);assert.equal(monthSales.product,213600);ledger.sales[1].price=25000;sandbox.api.setDailySale(ledger,'2026-10-01','bundle-1',11);assert.equal(sandbox.api.ledgerItems(ledger,10).find(r=>r.id==='bundle-1').price,19800);sandbox.api.setDailySale(ledger,'2026-10-03','bundle-1',1);assert.equal(sandbox.api.ledgerItems(ledger,10).find(r=>r.date==='2026-10-03').price,25000);sandbox.api.ensureLedgerYear(ledger).targets[9]=500000;let actual=sandbox.api.ledgerGraphState(ledger);assert.equal(calculate(actual).revenue,258400);assert.equal(sandbox.api.revenueTarget(actual).target,500000);assert.equal(actual.reviewEnabled,true);ledger.ledger.month=11;actual=sandbox.api.ledgerGraphState(ledger);assert.equal(calculate(actual).revenue,99000);assert.equal(actual.reviewEnabled,false);ledger.ledger.month=0;actual=sandbox.api.ledgerGraphState(ledger);assert.equal(actual.months,12);assert.equal(calculate(actual).revenue,357400);assert.equal(actual.reviewEnabled,true);assert.equal(sandbox.api.dailyTotals(sandbox.api.ledgerItems(ledger,0)).product,357400);ledger.sales.splice(1,1);assert.ok(sandbox.api.ledgerColumns(ledger).some(r=>r.id==='bundle-1'&&r.archived));const restored=validate(JSON.parse(JSON.stringify(ledger)));assert.equal(sandbox.api.dailyTotals(sandbox.api.ledgerItems(restored,0)).product,357400);assert.throws(()=>sandbox.api.setDailySale(ledger,'2026-02-29','bundle-0',1));assert.throws(()=>sandbox.api.setDailySale(ledger,'2026-10-04','bundle-0',-1));ledger.ledger.year=2027;ledger.ledger.month=10;actual=sandbox.api.ledgerGraphState(ledger);assert.equal(calculate(actual).revenue,0);assert.equal(actual.reviewEnabled,false);console.log('PASS: calendar/leap years, daily bundle quantities, month/year reconciliation, historical price snapshots, archived bundles, target months, one-time costs, backups and separate years');
const targetCase=defaults();targetCase.months=2;targetCase.sales[0].orders=100;targetCase.monthlyTarget=500000;let goal=sandbox.api.revenueTarget(targetCase);assert.equal(goal.target,1000000);assert.equal(goal.ratio,0.78);targetCase.monthlyTarget=300000;goal=sandbox.api.revenueTarget(targetCase);assert.equal(goal.ratio,1.3);assert.equal(goal.remaining,0);targetCase.monthlyTarget=0;assert.equal(sandbox.api.revenueTarget(targetCase).ratio,null);delete targetCase.monthlyTarget;validate(targetCase);assert.equal(targetCase.monthlyTarget,0);targetCase.monthlyTarget=-1;assert.throws(()=>validate(targetCase));console.log('PASS: target multiplied by months, 78% and 130% attainment, zero goal undefined, old backups migrated, invalid targets rejected');
const forecast=defaults();forecast.months=3;sandbox.api.setMonthlyOrders(forecast,1,100);sandbox.api.setMonthlyOrders(forecast,2,60);assert.equal(forecast.sales[1].orders,300);assert.equal(forecast.sales[2].orders,180);assert.equal(calculate(forecast).sold,1800);assert.equal(forecast.sales[0].orders,0);sandbox.api.setForecastMonths(forecast,2);assert.equal(forecast.sales[1].orders,200);assert.equal(forecast.sales[2].orders,120);assert.equal(calculate(forecast).sold,1200);sandbox.api.setMonthlyOrders(forecast,1,0);assert.equal(forecast.sales[2].orders,120);assert.throws(()=>sandbox.api.setMonthlyOrders(forecast,1,0.1));forecast.manufactureExtra=500000;sandbox.api.setUnitCost(forecast,2000);assert.ok(Math.abs(calculate(forecast).unit-2000)<1e-8);console.log('PASS: independent monthly bundle sets, period conversion, months retain bundle mix, other rows unchanged, invalid fractional period orders rejected');
const graph=defaults();let bars=sandbox.api.chartModel(graph);assert.equal(bars.length,8);assert.equal(bars[7].value,sandbox.api.operatingTotals(graph).period);graph.reviewEnabled=false;graph.ads.forEach(r=>r.enabled=false);graph.sales[1].orders=100;graph.fixed[0].rate=100000;bars=sandbox.api.chartModel(graph);assert.equal(Math.round(bars[7].value),772600);assert.ok(Math.abs(bars[1].value-bars.slice(2,7).reduce((a,r)=>a+r.value,0)-bars[7].value)<1e-6);graph.fixed[0].rate=1000000;assert.ok(sandbox.api.chartModel(graph)[7].value<0);graph.sales.forEach(r=>r.orders=0);graph.fixed.forEach(r=>r.rate=0);assert.ok(sandbox.api.chartModel(graph).every(r=>r.value===0));console.log('PASS: overview chart reconciles revenue minus all costs to net profit, responds to edits, handles losses and all-zero inputs');
const previousOrder=defaults();previousOrder.costOrder=Array.from({length:13},(_,i)=>12-i);validate(previousOrder);assert.equal(previousOrder.costOrder.length,10);assert.equal(previousOrder.costOrder[0],10);assert.ok(previousOrder.costOrder.every(i=>![2,11,12].includes(i)));console.log('PASS: old row-order backup migrates while totals remain pinned');
const reorder=defaults();reorder.months=3;reorder.sales[1].orders=100;reorder.fixed[0].rate=100000;const originalProfit=calculate(reorder).profit,op=sandbox.api.operatingTotals(reorder);assert.equal(op.period,originalProfit-300000);assert.equal(op.monthly,op.period/3);for(const group of ['sales','ads','admin','fixed','costOrder']){const first=JSON.stringify(reorder[group][0]);assert.equal(sandbox.api.moveRow(reorder,group,0,1),true);assert.equal(JSON.stringify(reorder[group][1]),first);assert.equal(sandbox.api.moveRow(reorder,group,0,-1),false);assert.equal(sandbox.api.moveRow(reorder,group,reorder[group].length-1,1),false);}assert.ok(Math.abs(calculate(reorder).profit-originalProfit)<1e-6);assert.equal(validate(JSON.parse(JSON.stringify(reorder))).costOrder[0],1);console.log('PASS: all five row groups reorder with values attached, boundary handling, backup order preserved, period/month-average profit deducts fixed costs');
const fixedCase=defaults();fixedCase.months=3;fixedCase.sales[1].orders=100;const beforeFixed=calculate(fixedCase);fixedCase.fixed[0].rate=1000000;fixedCase.fixed[1].rate=200000;fixedCase.fixed[2].enabled=false;fixedCase.fixed[2].rate=50000;const afterFixed=calculate(fixedCase),fixedResult=sandbox.api.fixedTotals(fixedCase);assert.equal(fixedResult.monthly,1200000);assert.equal(fixedResult.period,3600000);for(const k of ['total','profit','alloc','per','ad','admin'])assert.equal(beforeFixed[k],afterFixed[k]);const oldBackup=defaults();delete oldBackup.fixed;oldBackup.sales[0].orders=42;validate(oldBackup);assert.equal(oldBackup.fixed.length,5);assert.equal(oldBackup.sales[0].orders,42);fixedCase.fixed[0].rate=-1;assert.throws(()=>validate(fixedCase));console.log('PASS: separate fixed-cost monthly/period totals, disabled items, no impact on product cost/profit/allocation, old backup migration, invalid fixed costs');
const recurring=defaults();recurring.months=3;let r=calculate(recurring);assert.equal(r.reviewBase,4338000);assert.equal(Math.round(r.reviewProduct),2574000);assert.equal(r.monthlyAd,3795000);assert.equal(Math.round(r.ad),18297000);recurring.reviewEnabled=false;r=calculate(recurring);assert.equal(r.review,0);assert.equal(r.ad,11385000);recurring.ads.push({enabled:true,name:'one-time',cycle:'once',rate:100000,qty:1});r=calculate(recurring);assert.equal(r.onceAd,100000);assert.equal(r.ad,11485000);console.log('PASS: review charged once across 3 months, recurring ads multiplied, later period review excluded, other one-time ads charged once');
let c=calculate(s);assert.equal(c.unit,1716.0000000000002);assert.equal(Math.round(c.cash),10010000);assert.equal(c.reviewBase,4338000);assert.equal(Math.round(c.reviewProduct),2574000);assert.equal(Math.round(c.ad),10707000);assert.equal(c.per,null);
s.reviewProduct=false;c=calculate(s);assert.equal(c.ad,8133000);assert.equal(c.review,4338000);
s.reviewEnabled=false;s.ads.forEach(x=>x.enabled=false);s.sales[1].orders=100;c=calculate(s);assert.equal(c.sold,300);assert.equal(Math.round(c.cogs),514800);assert.equal(c.fee,237600);assert.equal(c.ship,300000);assert.equal(c.pack,55000);assert.equal(Math.round(c.profit),872600);assert.equal(Math.round(c.total),1107400);
s.admin[0].rate=100000;s.months=2;c=calculate(s);assert.equal(c.admin,200000);assert.equal(Math.round(c.profit),672600);
s.sales[1].shippingIncome=1000;c=calculate(s);assert.equal(c.shippingIncome,100000);assert.equal(Math.round(c.profit),772600);
s.sales[1].orders=-1;assert.throws(()=>validate(s));s.sales[1].orders=1.5;assert.throws(()=>validate(s));
console.log('PASS: syntax, reference manufacturing cash, advertising totals, missing sales, bundle profit, recurring administration, shipping income, invalid quantities');
const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{id,value:'',checked:false,innerHTML:'',textContent:'',addEventListener:()=>{},setAttribute:()=>{},click:()=>{},selectedOptions:[{text:'네오메디칼제약'}]});return elements.get(id);};let downloaded;
const ui={document:{getElementById:element,addEventListener:()=>{},createElement:()=>({click:()=>{}})},localStorage:{getItem:()=>null,setItem:()=>{}},Blob,URL:{createObjectURL:blob=>{downloaded=blob;return 'test';},revokeObjectURL:()=>{}},setTimeout:()=>{},alert:message=>{throw Error(message);},confirm:()=>true,window:{print:()=>{}}};vm.createContext(ui);vm.runInContext(js,ui);assert.ok(element('costs').innerHTML.includes('판매 제품 제조원가'));assert.ok(element('costSummary').innerHTML.includes('비용 총계 (고정비 제외)'));assert.ok(element('costSummary').innerHTML.includes('고정비 차감 후 이익'));assert.ok(!element('costSummary').innerHTML.includes('data-move'));assert.ok(element('adsSummary').innerHTML.includes('광고·마케팅 총계'));assert.ok(element('adminSummary').innerHTML.includes('제품 관리비 합계'));assert.ok(element('salesSummary').innerHTML.includes('판매계획 총계'));assert.equal(element('cash').textContent,'8,580,000 원');assert.equal(element('productTotalCost').textContent,'8,580,000');assert.equal(element('tubeProductionCost').textContent,'1,430,000');assert.ok(!html.includes('초도'));assert.equal(element('profit').textContent,element('operatingProfit').textContent);element('save').onclick();assert.ok(downloaded.size>0);element('csv').onclick();assert.ok(downloaded.size>0);element('addSale').onclick();assert.ok(element('forecastSales').innerHTML.includes('data-forecast-index="4"'));console.log('PASS: full initialization, rendering, JSON backup, CSV export, sale row addition (DOM simulation)');







