const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('outputs/보나센_원가계산기.html','utf8'),js=html.match(/<script>([\s\S]*?)<\/script>/)[1],elements=new Map(),handlers={};let saved;
const get=id=>{if(!elements.has(id))elements.set(id,{id,value:'',dataset:{},checked:false,innerHTML:'',textContent:'',addEventListener(){},setAttribute(){},click(){},selectedOptions:[{text:'네오메디칼제약'}]});return elements.get(id);};
const context={document:{getElementById:get,addEventListener:(n,fn)=>handlers[n]=fn,createElement:()=>({click(){}})},localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},setTimeout(){},confirm:()=>true,alert:m=>{throw Error(m);},window:{print(){}}};vm.createContext(context);vm.runInContext(js,context);
handlers.input({target:{id:'dashboardTarget',dataset:{},value:'500000'}});handlers.input({target:{id:'',dataset:{dailyDate:'2026-10-10',dailyBundle:'bundle-1'},value:'2'}});assert.equal(get('dashRevenue').textContent,'39,600 원');assert.equal(get('dashRate').textContent,'7.9%');assert.equal(get('dashSets').textContent,'2 세트');assert.equal(get('dashUnits').textContent,'제품 6개');assert.ok(get('manufacturingUnitHeadline').textContent.includes('10,296원'));assert.ok(get('sales').innerHTML.includes('누계 자동 연동'));
handlers.input({target:{id:'',type:'number',dataset:{group:'fixed',index:'0',key:'rate'},value:'100000'}});assert.equal(JSON.parse(saved).ledger.years['2026'].budgets['10'].fixed,100000);assert.ok(get('fixedExpenseHeadline').textContent.includes('100,000원'));
handlers.input({target:{id:'',dataset:{forecastIndex:'1',key:'monthlyOrders'},value:'100'}});assert.equal(get('dashRevenue').textContent,'39,600 원');assert.ok(get('expectedRevenueHeadline').textContent.includes('1,980,000원'));get('useExpectedTarget').onclick();assert.equal(get('dashGoal').textContent,'1,980,000 원');assert.equal(get('dashRate').textContent,'2.0%');
const h=html.split('<script>')[0];for(const label of ['1. 제품원가표','2. 광고·마케팅 비용','3. 월 관리비·고정경비','4. 월 예상매출과 일일 누계 달성현황'])assert.ok(h.includes(label));assert.ok(h.indexOf('보나센 매출 대시보드')<h.indexOf('1. 제품원가표'));const ids=[...h.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);
console.log('PASS: dashboard target/cumulative values and set breakdown, manufacturing formula, fixed-cost editing updates selected month, independent forecast quantity, forecast-to-target action, requested section order and unique IDs (DOM simulation)');
