from pathlib import Path
p=Path('outputs/보나센_원가계산기.html');s=p.read_text(encoding='utf-8')
def change(a,b):
 global s
 if a not in s: raise RuntimeError('Missing '+a[:90])
 s=s.replace(a,b)
change('<label>월 판매수량 (제품 개수)<input id="forecastMonthlyUnits" type="number" min="0" step="1"></label>', '')
change('월 판매수량을 변경하면 기존 묶음 판매비율을 최대한 유지하며, 남는 수량은 1개 구성에 반영합니다. 기존 판매계획이 없으면 1개 구성으로 계산합니다. 여러 달은 같은 월 판매수량을 가정합니다.', '아래 묶음별 월 판매 세트수를 각각 입력하세요. 예: 3개 묶음 100세트 = 제품 300개. 위쪽 주문수는 선택한 기간 전체 주문수이며, 아래는 월평균 세트수입니다. 월 세트수 × 개월수가 위쪽 주문수에 반영됩니다. 개월수 변경 시 묶음별 월평균을 유지하며 기간 주문수는 정수로 반올림합니다.')
change('<p id="forecastStatus"', '<div class="scroll"><table><thead><tr><th>묶음 구성</th><th>묶음 판매가</th><th>월 판매 세트수</th><th>판매수수료 (%)</th><th>건당 배송비</th><th>건당 포장비</th><th>고객 부담 배송비</th><th class="num">기간 주문수</th><th></th></tr></thead><tbody id="forecastSales"></tbody><tfoot id="forecastSalesSummary"></tfoot></table></div><button id="addForecastSale">판매구성 추가</button><p id="forecastStatus"')
start=s.index('function setMonthlyUnits(');end=s.index('function setUnitCost(',start)
s=s[:start]+'''function setMonthlyOrders(s,index,value){if(!Number.isInteger(index)||index<0||index>=s.sales.length)throw Error('판매구성을 확인하세요.');const period=value*s.months;if(!Number.isFinite(value)||value<0||Math.abs(period-Math.round(period))>1e-7)throw Error('월 판매 세트수 × 개월수가 0 이상의 정수가 되도록 입력하세요.');s.sales[index].orders=Math.round(period);}
function setForecastMonths(s,months){if(!Number.isInteger(months)||months<1)throw Error('적용 개월수는 1 이상의 정수로 입력하세요.');const orders=s.sales.map(r=>Math.round(r.orders/s.months*months));s.months=months;s.sales.forEach((r,i)=>r.orders=orders[i]);}
function renderForecastSales(s){const active=document.activeElement;if(!active||!active.dataset||active.dataset.forecastIndex===undefined){$('forecastSales').innerHTML=s.sales.map((r,i)=>{const field=(key,value)=>`<input type="number" min="${key==='units'?1:0}" step="${key==='units'?1:'any'}" ${key==='fee'?'max="100"':''} value="${value}" data-forecast-index="${i}" data-key="${key}" aria-label="${r.units}개 묶음 ${key==='monthlyOrders'?'월 판매 세트수':key}">`;return `<tr><td>${field('units',r.units)}</td><td>${field('price',r.price)}</td><td>${field('monthlyOrders',r.orders/s.months)}</td><td>${field('fee',r.fee)}</td><td>${field('ship',r.ship)}</td><td>${field('pack',r.pack)}</td><td>${field('shippingIncome',r.shippingIncome)}</td><td class="num" id="forecastOrders-${i}"></td><td>${orderButtons('sales',i,s.sales.length)}</td></tr>`;}).join('');}s.sales.forEach((r,i)=>$('forecastOrders-'+i).textContent=money(r.orders)+'セット'.replace('セット','세트'));const c=calculate(s);$('forecastSalesSummary').innerHTML=`<tr class="result"><td colspan="2">월 판매 합계</td><td class="num">${(c.orders/s.months).toLocaleString('ko-KR',{maximumFractionDigits:4})}세트</td><td colspan="4">제품 ${(c.sold/s.months).toLocaleString('ko-KR',{maximumFractionDigits:4})}개 / 월</td><td class="num">기간 ${money(c.orders)}세트</td><td></td></tr>`;}
''' +s[end:]
change("function renderChart(s){const totals=calculate(s);if(document.activeElement!==$('forecastMonthlyUnits'))$('forecastMonthlyUnits').value=Number((totals.sold/s.months).toFixed(4));", "function renderChart(s){renderForecastSales(s);const totals=calculate(s);")
change("['forecastMonthlyUnits','forecastUnitCost','forecastMonths']", "['forecastUnitCost','forecastMonths']")
change("if(el.id==='forecastMonthlyUnits')setMonthlyUnits(state,value);", '')
change("if(el.id==='forecastMonths'){if(!Number.isInteger(value)||value<1)throw Error('적용 개월수는 1 이상의 정수로 입력하세요.');const monthly=calculate(state).sold/state.months;state.months=value;if(Number.isInteger(monthly)&&state.sales.some(r=>r.units===1))setMonthlyUnits(state,monthly);}", "if(el.id==='forecastMonths')setForecastMonths(state,value);")
change("const el=e.target;if(['forecastUnitCost'", "const el=e.target;if(el.dataset.forecastIndex!==undefined){try{if(el.value==='')throw Error('값을 입력하세요.');validate(state);const index=Number(el.dataset.forecastIndex),value=Number(el.value),key=el.dataset.key;if(key==='monthlyOrders')setMonthlyOrders(state,index,value);else{if(!['units','price','fee','ship','pack','shippingIncome'].includes(key)||!Number.isFinite(value)||value<0||key==='units'&&(!Number.isInteger(value)||value<1)||key==='fee'&&value>100)throw Error('구성 수량·금액·수수료를 확인하세요.');state.sales[index][key]=value;}render();$('forecastStatus').textContent='묶음별 판매계획과 그래프에 반영했습니다.';$('forecastStatus').className='note';}catch(err){$('forecastStatus').textContent=err.message+' 기존 계산값은 유지됩니다.';$('forecastStatus').className='warn';}return;}if(['forecastUnitCost'")
change("$('addSale').onclick=()=>", "$('addForecastSale').onclick=()=>$('addSale').onclick();\n$('addSale').onclick=()=>")
change("money(r.orders)+'セット'.replace('セット','세트')", "money(r.orders)+'세트'")
p.write_text(s,encoding='utf-8');print('Forecast now mirrors each bundle with monthly sets, pricing, fees and shipping; syncs each row independently')
