from pathlib import Path
p=Path('outputs/보나센_원가계산기.html')
s=p.read_text(encoding='utf-8')
def change(old,new):
    global s
    if old not in s: raise RuntimeError('Missing source: '+old[:100])
    s=s.replace(old,new)
change('<section><h2>5. 원가표와 손익</h2>', '''<section><h2>5. 월 고정비 (별도 비용)</h2><p class="notice">이 표의 고정비는 제품 총원가, 광고·관리비 배부, 묶음별 이익 및 기간 총 비교이익에 포함하지 않습니다. 사업 운영비를 별도로 확인하는 표입니다.</p><p class="note">매월 발생하는 부가세 포함 금액을 입력하세요. 공용 비용도 여기에서 별도로 관리할 수 있습니다. 같은 비용을 위 관리비에도 입력하면 해당 관리비 금액은 제품 원가에 포함되므로 중복 입력하지 마세요.</p><div class="scroll"><table><thead><tr><th>포함</th><th>항목</th><th>월 금액 (원)</th><th class="num">기간 금액 (원)</th><th></th></tr></thead><tbody id="fixed"></tbody><tfoot><tr><td colspan="2">고정비 합계</td><td class="num" id="fixedMonthly">0</td><td class="num" id="fixedPeriod">0</td><td></td></tr></tfoot></table></div><p class="note" id="fixedSummary"></p><button id="addFixed">고정비 항목 추가</button></section><section><h2>6. 원가표와 손익</h2>''')
change('공용 인건비·임대료는 보나센 부담분만 입력하세요.', '제품 원가에 반영할 보나센 부담분만 입력하세요. 별도로 확인할 임대료·전기료·통신료 등은 아래 월 고정비 표에 입력하세요.')
change("admin:[{enabled:true,name:'보관료'", "fixed:['임대료','전기료','수도·가스료','통신료','기타잡비'].map(name=>({enabled:true,name,rate:0})),admin:[{enabled:true,name:'보관료'")
change("name:'인건비·임대료 배부'", "name:'제품 관리 인건비 배부'")
change("const key='bonasen-cost-v1';let state=defaults(),storageOK=true;try{const v=localStorage.getItem(key);if(v)state=validate(JSON.parse(v));}catch(e){storageOK=false;}", "const key='bonasen-cost-v1';let state=defaults(),storageOK=true;")
change("function validate(v){const d=defaults();", "function validate(v){const d=defaults();if(v&&v.version===1&&v.fixed===undefined)v.fixed=d.fixed;")
change("throw Error('비용 항목 오류');return v;}", "throw Error('비용 항목 오류');if(!Array.isArray(v.fixed))throw Error('고정비 형식 오류');for(const r of v.fixed)if(typeof r.enabled!=='boolean'||typeof r.name!=='string'||typeof r.rate!=='number'||!Number.isFinite(r.rate)||r.rate<0)throw Error('고정비는 0 이상의 숫자로 입력하세요.');return v;}\ntry{const saved=localStorage.getItem(key);if(saved)state=validate(JSON.parse(saved));}catch(e){storageOK=false;}")
change("function input(value,k,group,i,extra='')", "function fixedTotals(s){const monthly=s.fixed.reduce((sum,r)=>sum+(r.enabled?r.rate:0),0);return{monthly,period:monthly*s.months};}\nfunction input(value,k,group,i,extra='')")
change(".join('');update();}", ".join('');$('fixed').innerHTML=state.fixed.map((r,i)=>`<tr><td><input type=\"checkbox\" ${r.enabled?'checked':''} data-group=\"fixed\" data-index=\"${i}\" data-key=\"enabled\" aria-label=\"고정비 포함\"></td><td><input class=\"name\" value=\"${escapeHTML(r.name)}\" data-group=\"fixed\" data-index=\"${i}\" data-key=\"name\" aria-label=\"고정비 항목\"></td><td>${input(r.rate,'rate','fixed',i)}</td><td class=\"num\" id=\"fixed-${i}\"></td><td><button data-remove=\"fixed\" data-index=\"${i}\" aria-label=\"고정비 삭제\">삭제</button></td></tr>`).join('');update();}")
change("$('costs').innerHTML='';$('bundles').innerHTML='';return;", "$('costs').innerHTML='';$('bundles').innerHTML='';$('fixedMonthly').textContent='—';$('fixedPeriod').textContent='—';$('fixedSummary').textContent='입력값을 확인하세요.';state.fixed.forEach((r,i)=>{if($('fixed-'+i))$('fixed-'+i).textContent='—';});return;")
change("$('unit').textContent=money(c.per)+' 원';", "const fixed=fixedTotals(state);$('fixedMonthly').textContent=money(fixed.monthly);$('fixedPeriod').textContent=money(fixed.period);$('fixedSummary').textContent='월 고정비 '+money(fixed.monthly)+'원 × '+state.months+'개월 = 별도 기간 비용 '+money(fixed.period)+'원 (제품 원가·비교이익에서 제외)';state.fixed.forEach((r,i)=>$('fixed-'+i).textContent=money(r.enabled?r.rate*state.months:0));$('unit').textContent=money(c.per)+' 원';")
change("$('addSale').onclick=", "$('addFixed').onclick=()=>{state.fixed.push({enabled:true,name:'새 고정비',rate:0});render();};\n$('addSale').onclick=")
change("['리뷰','리뷰 부대비','','','',c.reviewBase]", "['리뷰','리뷰 부대비','','','',c.reviewBase]")
change("[],['판매구성','판매가'", "[],['별도 월 고정비 (제품 원가·비교이익에서 제외)','월 금액','기간 금액'],...state.fixed.map(r=>[r.name,r.enabled?r.rate:0,r.enabled?r.rate*state.months:0]),['고정비 합계',fixedTotals(state).monthly,fixedTotals(state).period],[],['판매구성','판매가'")
change('추가 튜브는 예비 자재로서 초도 필요자금에만 반영합니다.', '월 고정비 표의 금액은 제품 원가와 모든 비교이익에서 제외하며 별도 비용으로만 표시합니다.<br>추가 튜브는 예비 자재로서 초도 필요자금에만 반영합니다.')
p.write_text(s,encoding='utf-8')
print('Added separate monthly fixed costs, independent of product costs and profits; preserved previous saved inputs')
